### ISSUE TITLE
desaturated icons only on the "out of range" part of the addon

### ISSUE THREAD

**Issue by dnlpz** [tullamods/tullaRange#13]
Since yesterday, out of range abilities gets desaturated. Been with this addon, and its updates, since years. Never happened.
![tullabug](https://user-images.githubusercontent.com/119383957/206936438-0ac425df-8f8c-4b23-8e52-fd9f218ba2ba.png)

**Comment by Guema** [comment]
You are right, while i like this aspect, i understand some people may not enjoy it in those kind of situations
I was thinking about some checkbox allowing to desaturate or not in each situation based on user choice

@Tuller is it something you would accept as PR ? (i'm ok to work on it myself as if we agree on the principle, i'll try to mimic the "default config" behviour, and by default it will be on for "oom" and "oor" but not on "disabled")

**Comment by dnlpz** [comment]
What I am referring to is that I have been with Tullarange for years and desaturation never happened until yesterday.

**Comment by Tuller** [comment]
Yes, working on a PR for this would be fine.

**Comment by Tuller** [comment]
> What I am referring to is that I have been with Tullarange for years and desaturation never happened until yesterday.

Are you running the latest version? I did adjust it to not affect unusable yesterday

**Comment by dnlpz** [comment]
If its intended wouldnt be ideal to put an option to desature or not desature? I dont dislike desaturation btw. 

Thank you for the great work.

**Comment by Guema** [comment]
It is intentional.

I made a test because i had some of my spells rendering like nearly full black square.

Then i proposed it as pr.
Here is an explanation of why : #12
