### ISSUE TITLE
Not working with (all?) Masque styles?

### ISSUE THREAD

**Issue by 40P3** [tullamods/tullaRange#20]
Hi,

I noticed after changing to some masque styles on "default" mainbar that tullaRange stopped working. Is there a way to "generalise" tullaRange so it would work with all the masque styles or I should just revert back to standard style on the bar or this might be a bug and its WIP?

I'm using Masque, with all the available skins installed and Masque Blizzard Bars.
Masque Blizzard Bars: https://www.curseforge.com/wow/addons/masque-blizz-bars-revived
Masque: https://www.curseforge.com/wow/addons/masque

**Comment by Tuller** [comment]
Is this on Dragonflight or classic? I've not yet reproduced any issues on my end. My guess is that if you add the following line to tullaRange.toc then it'll work:
```
## OptionalDeps: Masque
```

**Comment by 40P3** [comment]
Hi Tuller,

Sorry for the very long response time please forgive me!
Yes it was Dragon...
So not sure what happened. I was trying to reverse-enginer the issue, and I couldn't.
Strangely all on my toons (tried all classes I couldn't remember on which class I had this issue lol), and changed around the installed styles, but for the life of me I couldn't find which one had the issue.

So I don't wan't you to say I'm the boy shouting Wolf when there isn't any wolf sorry. 🗡️ Don't Kill me! :)

OR, might be that some other update on addons (masque had one or two in the past week I think?) could have fixed it, not sure. But again I only was experiencing this problem once. So its weird.

I think we can close this issue for now. Thanks for taking the time replying and checking it yourself appreciate it!
BTW: LOVE LOVE LOVE the addon! /hugs

Have a happy new year!
Regards,
H0PE
