### ISSUE TITLE
Consistancy between death and flying?

### ISSUE THREAD

**Issue by rakkarage** [tullamods/tullaRange#21]
![WoWScrnShot_011223_212625](https://user-images.githubusercontent.com/962340/212240709-1e7303fa-a16e-41a1-84c8-fff331356f7c.jpg)
![WoWScrnShot_011223_202534](https://user-images.githubusercontent.com/962340/212240715-70ac394b-ec74-4830-a30a-d8a540999b58.jpg)

more buttons are "available" when dead then flying?

**Comment by rakkarage** [comment]
cant replicate all the time idk sorry

**Comment by rakkarage** [comment]
ya while on flight path evrything is disabled, but while dead is not?

**Comment by Tuller** [comment]
This  one is more reflective of issues with WoW's APIs.
