### ISSUE TITLE
Error after 11.0.0 update

### ISSUE THREAD

**Issue by 40P3** [tullamods/tullaRange#35]
Many thanks for the update I was waiting for it like a Messiah! :D
Still error:
1x tullaRange_Config/colorOptions.lua:83: attempt to index local 'selector' (a nil value)
[string "@tullaRange_Config/colorOptions.lua"]:83: in function `UpdateWidgets'
[string "@tullaRange_Config/colorOptions.lua"]:42: in function <tullaRange_Config/colorOptions.lua:41>
[string "=[C]"]: in function `Show'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:968: in function `DisplayLayout'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:909: in function `DisplayCategory'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:851: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:844>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_Settings_Shared/Blizzard_CategoryList.lua"]:143: in function <...s/Blizzard_Settings_Shared/Blizzard_CategoryList.lua:141>

Locals:
self = tullaRange_ColorOptions {
 name = "tullaRange"
}
(for state) = <table> {
 1 = "oor"
 2 = "oom"
 3 = "unusable"
}
(for control) = 1
_ = 1
type = "oor"
selector = nil
(*temporary) = tullaRange_ColorOptions {
 name = "tullaRange"
}
(*temporary) = nil
(*temporary) = "attempt to index local 'selector' (a nil value)"

**Comment by 40P3** [comment]
3x tullaRange_Config/colorOptions.lua:96: attempt to index field 'ColorSelector' (a nil value)
[string "@tullaRange_Config/colorOptions.lua"]:96: in function `CreateColorSelector'
[string "@tullaRange_Config/colorOptions.lua"]:54: in function `AddWidgets'
[string "@tullaRange_Config/colorOptions.lua"]:32: in function `Load'
[string "@tullaRange_Config/colorOptions.lua"]:111: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@tullaRange/tullaRange.lua"]:26: in function <tullaRange/tullaRange.lua:25>
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:483: in function `SetUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:290: in function `ShowUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:169: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:164>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:874: in function `ShowUIPanel'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:377: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:375>
[string "=(tail call)"]: ?
[string "@Blizzard_GameMenu/Standard/GameMenuFrame.lua"]:68: in function <Blizzard_GameMenu/Standard/GameMenuFrame.lua:65>

Locals:
self = tullaRange_ColorOptions {
 name = "tullaRange"
}
type = "oor"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'ColorSelector' (a nil value)"
Addon = <table> {
 Slider = Slider {
 }
 L = <table> {
 }
 ColorOptions = tullaRange_ColorOptions {
 }
 OptionsPanel = Frame {
 }
}

**Comment by 40P3** [comment]
3x ...etullaRange_Config/widgets/colorSelector.lua:99: attempt to call global 'GetSpellBookItemTexture' (a nil value)
[string "@tullaRange_Config/widgets/colorSelector.lua"]:99: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@tullaRange/tullaRange.lua"]:26: in function <tullaRange/tullaRange.lua:25>
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:483: in function `SetUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:290: in function `ShowUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:169: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:164>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:874: in function `ShowUIPanel'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:377: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:375>
[string "=(tail call)"]: ?
[string "@Blizzard_GameMenu/Standard/GameMenuFrame.lua"]:68: in function <Blizzard_GameMenu/Standard/GameMenuFrame.lua:65>

Locals:
_ = "tullaRange_Config"
Addon = <table> {
 L = <table> {
 }
}
L = <table> {
 oor = "Out of Range"
 Blue = "Blue"
 oom = "Out of Mana"
 Desaturate = "Desaturate"
 Green = "Green"
 unusable = "Unusable"
 ColorSettingsTitle = "tullaRange color configuration settings"
 ColorSettings = "Colors"
 Red = "Red"
}
tullaRange = <table> {
 sets = <table> {
 }
 frame = Frame {
 }
}
ColorChannels = <table> {
 1 = "Red"
 2 = "Green"
 3 = "Blue"
 4 = "Opacity"
}
ColorSelector = Frame {
 mt = <table> {
 }
}
SpellIcons = <table> {
}
(for index) = 1
(for limit) = 5
(for step) = 1
i = 1
_ = "General"
_ = 136830
offset = 0
numSlots = 20
tabEnd = 20
(for index) = 0
(for limit) = 19
(for step) = 1
j = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = "player"
(*temporary) = "attempt to call global 'GetSpellBookItemTexture' (a nil value)"

**Comment by b-morgan** [comment]
(I think this is a duplicate)
1x tullaRange_Config/colorOptions.lua:96: attempt to index field 'ColorSelector' (a nil value)
[string "@tullaRange_Config/colorOptions.lua"]:96: in function `CreateColorSelector'
[string "@tullaRange_Config/colorOptions.lua"]:54: in function `AddWidgets'
[string "@tullaRange_Config/colorOptions.lua"]:32: in function `Load'
[string "@tullaRange_Config/colorOptions.lua"]:111: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@tullaRange/tullaRange.lua"]:26: in function <tullaRange/tullaRange.lua:25>
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:483: in function `SetUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:290: in function `ShowUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:169: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:164>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:874: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:852>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:377: in function `Open'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:384: in function `OpenToCategory'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:130: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:127>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:31: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:30>
[string "=(tail call)"]: ?
[string "@Skillet/Skillet.lua"]:1610: in function `ShowOptions'
[string "*MainFrame.xml:962_OnClick"]:2: in function <[string "*MainFrame.xml:962_OnClick"]:1>

Locals:
self = tullaRange_ColorOptions {
 name = "tullaRange"
}
type = "oor"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'ColorSelector' (a nil value)"
Addon = <table> {
 Slider = Slider {
 }
 L = <table> {
 }
 ColorOptions = tullaRange_ColorOptions {
 }
 OptionsPanel = Frame {
 }
}

**Comment by Tuller** [comment]
This was fixed in 11.0.0
