### ISSUE TITLE
11.0.2 LUA spam

### ISSUE THREAD

**Issue by vezevez** [tullamods/tullaRange#37]
Many errors with the new patch :(

5x tullaRange/actionState.lua:48: attempt to call global 'IsUsableSpell' (a nil value)
[string "@tullaRange/actionState.lua"]:48: in function `GetPetActionState'
[string "@tullaRange/updater.modern.lua"]:158: in function <tullaRange/updater.modern.lua:157>
[string "@tullaRange/updater.modern.lua"]:257: in function <tullaRange/updater.modern.lua:248>
[string "=[C]"]: ?
[string "=[C]"]: in function `Update'
[string "@Blizzard_ActionBar/Mainline/PetActionBar.lua"]:86: in function <Blizzard_ActionBar/Mainline/PetActionBar.lua:70>
[string "=[C]"]: ?

Locals:
slot = 4
_ = "Dash"
_ = 132120
_ = nil
_ = false
_ = true
_ = true
spellID = 61684
checksRange = false
inRange = false
oor = false
(*temporary) = nil
(*temporary) = 61684
(*temporary) = "attempt to call global 'IsUsableSpell' (a nil value)"

**Comment by RangerTure** [comment]
Same

11x tullaRange/actionState.lua:48: attempt to call global 'IsUsableSpell' (a nil value)
[string "@tullaRange/actionState.lua"]:48: in function `GetPetActionState'
[string "@tullaRange/updater.modern.lua"]:158: in function <tullaRange/updater.modern.lua:157>
[string "@tullaRange/updater.modern.lua"]:257: in function <tullaRange/updater.modern.lua:248>
[string "=[C]"]: ?
[string "=[C]"]: in function `Update'
[string "@Blizzard_ActionBar/Mainline/PetActionBar.lua"]:74: in function <Blizzard_ActionBar/Mainline/PetActionBar.lua:70>
[string "=[C]"]: ?

Locals:
slot = 4
_ = "Bite"
_ = 132127
_ = nil
_ = false
_ = true
_ = true
spellID = 17253
checksRange = false
inRange = false
oor = false
(*temporary) = nil
(*temporary) = 17253
(*temporary) = "attempt to call global 'IsUsableSpell' (a nil value)"

**Comment by vezevez** [comment]
looks like it's fixed with the newest update :) thank you tulla

**Comment by stako** [comment]
still causing problems on Cataclysm Classic.

fixed by changing this
`local _, oom = (IsSpellUsableor C_Spell.IsSpellUsable)(spellID)`
to this
`local _, oom = (IsUsableSpell or C_Spell.IsSpellUsable)(spellID)`

not sure if the `C_Spell.IsSpellUsable` portion is correct. I believe that's just for retail which I haven't got installed
