### ISSUE TITLE
LUA Errors (Detected with BugSack)

### ISSUE THREAD

**Issue by Akrololz** [tullamods/tullaRange#38]
3596x tullaRange/actionState.lua:22: attempt to get length of local 'costs' (a nil value)
[string "@tullaRange/actionState.lua"]:22: in function <tullaRange/actionState.lua:7>
[string "@tullaRange/actionState.lua"]:37: in function `GetActionState'
[string "@tullaRange/updater.modern.lua"]:21: in function <tullaRange/updater.modern.lua:20>
[string "=[C]"]: in function `UpdateUsable'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:1015: in function `OnEvent'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:207: in function <Blizzard_ActionBar/Mainline/ActionButton.lua:204>

Locals:
slot = 26
actionType = "macro"
id = 25
name = "#M"
spellID = 360954
costs = nil
(*temporary) = 1
(*temporary) = 360954
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to get length of local 'costs' (a nil value)"

**Comment by Tuller** [comment]
I didn't catch that the new version of  [GetSpellPowerCost](https://warcraft.wiki.gg/wiki/API_C_Spell.GetSpellPowerCost) may return nil instead of always returning a table. Fortunately this is a simple fix.
