### ISSUE TITLE
Stance dancing/form cancelling macro support

### ISSUE THREAD

**Issue by merijn** [tullamods/tullaRange#6]
I have a number of macros on my warrior and druid that change stance/cancel form when pressed. Currently those "incorrectly" show up as being unusable (because wrong stance/form). Looking at the callback/colouring logic, it seems fairly straightforward to patch the tullaRange logic to handle this.

My idea was to simply: check if a button is a macro, if yes, check if it has some magic tag/name that enables this altered colouring, and then use a slightly reordered version of the colouring logic to colour the button as if I'm in the right stance/form. I can easily implement a patch for that, but I dislike maintaining my own patches indefinitely, so I was wondering what your concerns/opinions/requirements for merging such a change would be.

**Comment by Tuller** [comment]
The # in the macro name seems the best for now. The only other thing I could think of would be to do something like #ignorerange in the macro itself, but that would eat into the size of it.

**Comment by Tuller** [comment]
I've optimized the check slightly, and it is now in the latest release
