### ISSUE TITLE
Does not work with either Bartender4 or the whole Burning Crusade Classic version of the game

### ISSUE THREAD

**Issue by LtqxWYEG** [tullamods/tullaRange#8]
Hello

it just doesn't work. The addon is loaded and configured correctly, afaik. I am using Bartender4. It worked fine in ye olden Classic game.

**Comment by Tuller** [comment]
Bartender (well LibActionButton, which Bartender uses) actually implements range coloring, so you don't need tullaRange when using it.

**Comment by LtqxWYEG** [comment]
I can't find that. The only thing that's colored is the hotkey text
